website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.institucional.urls')),
    path('usuarios/', include('website.usuarios.urls')),
    path('area/', include('website.area_administrativa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/usuarios/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('cadastro/', views.cadastrar_usuario, name='cadastro'),
    path('login/', views.login_usuario, name='login'),
    path('logout/', views.logout_usuario, name='logout'),
    # path('area/', views.area_restrita, name='area_restrita'),
]

website/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.db import models

class Usuario(AbstractUser):
    # Campos adicionais, se quiser

    avatar = models.ImageField(
        upload_to="avatar/",   # pasta dentro de MEDIA_ROOT
        blank=True,
        null=True
    )

    data_nascimento = models.DateField(null=True, blank=True)
    bio = models.TextField(blank=True, null=True)    

    eh_mestre = models.BooleanField(default=False)
    eh_jogador = models.BooleanField(default=True)
                                   
    slug = models.SlugField('slug')
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.username)
            slug = base_slug
            counter = 1
            while Usuario.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'usuários'
        verbose_name = 'usuário'
        ordering = ('-criado_em',)

    def __str__(self):
        return f'{self.username}'

website/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.urls import reverse

Usuario = get_user_model()

def cadastrar_usuario(request):
    erro = None
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        avatar_img = request.FILES.get("avatar")  # pega o arquivo
        bio = request.POST.get("bio")
        data_nascimento = request.POST.get('data')

        # validações manuais
        if not username or not email or not password1:
            erro = "Preencha todos os campos."
        elif password1 != password2:
            erro = "As senhas não conferem."
        elif Usuario.objects.filter(username=username).exists():
            erro = "Esse nome de usuário já existe."
        else:
            # cria o usuário
            user = Usuario.objects.create_user(
                username=username,
                email=email,
                password=password1,
                avatar =  avatar_img if avatar_img else "" ,                
                bio=bio,
                data_nascimento=data_nascimento
            )

            
            user.save()

            login(request, user)
            return redirect('home_area_restrita')

    return render(request, "cadastro.html", {"erro": erro})


def login_usuario(request):
    erro = None
    if request.method == "POST":
        nome = request.POST.get("username")
        senha = request.POST.get("password")
        user = authenticate(request, username=nome, password=senha)
        if user is not None:
            login(request, user)
            return redirect("home_area_restrita")
        else:
            erro = "Usuário ou senha inválidos."
            return render(request, "login.html", {"erro": erro})
    return render(request, "login.html")



def logout_usuario(request):
    request.session.flush()
    return redirect(reverse('home'))
 


# @login_required
# def area_restrita(request):
#     return render(request, "area_restrita.html")

website/usuarios/templates/cadastro.html
{% extends 'base.html' %}
{% load static %}

{% block 'conteudo' %}
<div class="container">
    {% if messages %}
        {% for message in messages %}
        <br>
            <section class="alert {{message.tags}}">
                {{message}}
            </section>
        {% endfor %}
    {% endif %}    
    {{usuario_dados}}
<h2>Registrar Usuário</h2>
{% if erro %}<p style="color:red;">{{ erro }}</p>{% endif %}
  <form  method="post" class="formulario"  enctype="multipart/form-data"> {% csrf_token %}
    <input type="hidden" name="user" value={{user.username}}>
    <label>Username:</label><br>
    <input type="text" class="pergunta" name="username" id="username" placeholder="Username" value="{{usuario_dados.username}}" required><br>
    <label>Avatar:</label><br>
    <input type="file" class="pergunta" name="avatar" id="avatar" placeholder="..."><br>
    <label>Email:</label><br>
    <input type="email" class="pergunta" name="email" id="email" value="{{usuario_dados.email}}" placeholder="seu_email@gmail.com"><br>
    <label>Senha:</label><br>
    <input type="password" class="pergunta" value="{{usuario_dados.senha}}" name="password1" id="senha" placeholder="Insira sua senha..."><br>
    <label>Confirme sua senha:</label><br>
    <input type="password" class="pergunta" name="password2" id="senha2" placeholder="Confirme sua senha..."><br>
    <label>Eh mestre?:</label><br>
    <input class="form-check-input" type="checkbox" name="eh_mestre"  id="myCheckboxMestre" {% if usuario_dados.mestre %}checked{% endif %} value="mestre"><br>
    <textarea  class="pergunta" placeholder="Biografia..." name="bio" id="bio" cols="30" rows="10"></textarea><br>
    <label for="data" class="form-label">Data</label><br>
    <input  type="date" class="pergunta" name="data" id="data" placeholder="..."><br>
    
    <button class="botao-tema" type="submit">Salvar Contato</button> 

      <a href="{% url 'accounts:login' %}">Já tenho conta</a>
  </form>
</div>
{% endblock %}

website/usuarios/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block 'conteudo' %}
    <h2>Login</h2>
    {% if erro %}<p style="color:red;">{{ erro }}</p>{% endif %}
    <form class="formulario" method="post">
        {% csrf_token %}
        <div class="col-12">
              <label for="username" class="form-label">Nome de usuário</label> 
              <div class="input-group has-validation">
                  <input type="text" class="form-control" name="username" id="username"required> 
                  <div class="invalid-feedback">
                      Your username is required.
                  </div>
              </div>
          </div>
          <br>
          <br>
          <div class="col-12">
              <label for="username" class="form-label">Senha</label> 
              <div class="input-group has-validation">
                  <input type="text" class="form-control" name="username" id="username"required> 
                  <div class="invalid-feedback">
                      Your username is required.
                  </div>
              </div>
          </div>  
          <br>
        <!-- <label>Usuário:</label>
        <input class="pergunta" type="text" name="username"><br>
        <label>Senha:</label>
        <input class="pergunta" type="password" name="password"><br> -->
        <button class="botao_criar_personagem" type="submit">Entrar</button>
        <br>
        <br>
        <p class="letra_pequena">Ainda não tem uma conta? <a href="{% url 'accounts:cadastro' %}">Crie uma conta!</a></p>
    </form>
    
{% endblock %}